
export interface Vector2D {
  x: number;
  y: number;
}

export interface Leg {
  id: string;
  hipOffset: Vector2D;
  footPos: Vector2D;
  kneePos: Vector2D;
  stepStart: Vector2D;
  stepTarget: Vector2D;
  stepProgress: number; // 0 to 1
  isStepping: boolean;
}

export interface InternalLetter {
  id: string;
  char: string;
  pos: Vector2D;
  targetOffset: Vector2D; // Position relative to word center
  isSettled: boolean;
  opacity: number;
}

export interface SwallowedWord {
  id: string;
  text: string;
  pos: Vector2D;
  rotation: number;
  targetAnchor: 'core' | 'FL' | 'FR' | 'BL' | 'BR';
  letters: InternalLetter[];
  isComplete: boolean;
}

export interface DraggableWord {
  id: string;
  text: string;
  pos: Vector2D;
  originalPos: Vector2D;
  isDragging: boolean;
  isLocked: boolean;
}

export enum EatingState {
  IDLE = 'IDLE',
  ATTACHING = 'ATTACHING',
  EATING_LETTERS = 'EATING_LETTERS'
}

export interface ActiveLetterFeed {
  char: string;
  pos: Vector2D;
  targetAnchor: 'core' | 'FL' | 'FR' | 'BL' | 'BR';
  wordId: string;
  slotIndex: number;
  progress: number;
}

export interface SpeechBubble {
  text: string;
  opacity: number;
  timer: number;
}

export type DigestionStage = 'fresh' | 'digesting' | 'absorbed';

export interface DigestionRecord {
  id: string;
  text: string;
  stage: DigestionStage;
  timer: number;
  digestDuration: number;
  applied: boolean;
  absorbedAge: number;
}

export interface SoulAxes {
  calm: number;
  tender: number;
  poetic: number;
  curious: number;
  bold: number;
  orderly: number;
  hopeful: number;
  social: number;
  focused: number;
  stubborn: number;
}

export interface SoulIdentity {
  mood: string;
  preferences: string[];
  aversions: string[];
  fears: string[];
  values: string[];
  cravings: string[];
}

export interface WormSoul {
  axes: SoulAxes;
  targetAxes?: SoulAxes; // For gradual personality shifts
  identity: SoulIdentity;
  motto: string;
  absorbedCount: number;
}

// Background Text Types
export interface Letter {
  char: string;
  x: number;
  y: number;
  tokenId: string;
}

export interface Token {
  id: string;
  text: string;
  x: number;
  y: number;
  width: number;
  height: number;
  state: 'present' | 'eaten';
  letters: Letter[];
  isHovered?: boolean;
}

export interface TextBlock {
  id: string;
  tokens: Token[];
  x: number;
  y: number;
  width: number;
  height: number;
}

// Worm Lifecycle & Reproduction Types
export interface Worm {
  id: string;
  name?: string;              // Optional name generated by Gemini
  generation: number;         // 0 = original, 1 = first child, etc.
  parentId: string | null;
  birthTime: number;

  // Appearance (inherited with mutations)
  hue: number;               // 0-360 for color variation
  visualColor?: { h: number, s: number, l: number }; // Current interpolated color
  sizeMultiplier: number;    // 0.8-1.2 for size variation
  thickness: number;         // 0.1-0.5 for skin thickness (isoThreshold)
  speedMultiplier: number;   // Movement speed

  // Lifecycle
  satiation: number;         // 0-100, increases when eating
  health: number;            // 0-100, decreases over time
  lastMeal: number;          // timestamp

  // State (existing blob state)
  corePos: Vector2D;
  coreVel: Vector2D;
  legs: Leg[];
  targetPos: Vector2D;
  isHoveringEdible: boolean;

  // Vocabulary (from DigestionSystem)
  vocabulary: Set<string>;
  swallowedWords: SwallowedWord[];
  digestionQueue: DigestionRecord[];
  soul: WormSoul;
}

export interface WormState {
  worms: Map<string, Worm>;
  activeWormId: string;
  nextWormId: number;
}
